server:
  port: 8080

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


